apiVersion: apps/v1
kind: Deployment
metadata:
  name: vllm-client
spec:
  selector:
    matchLabels:
      app: vllm-client
  template:
    metadata:
      labels:
        app: vllm-client
    spec:
       containers:
       - name: gradio
         image: us-docker.pkg.dev/google-samples/containers/gke/gradio-app:v1.0.0
         resources:
          requests:
            cpu: "512m"
            memory: "512Mi"
          limits:
            cpu: "1"
            memory: "512Mi"
         env:
         - name: CONTEXT_PATH
           value: "/generate"
         - name: HOST
           value: "http://llm-service:8000"
         - name: LLM_ENGINE
           value: "vllm"
         - name: MODEL_ID
           value: "gemma"
         - name: USER_PROMPT
           value: "<start_of_turn>user\nprompt<end_of_turn>\n"
         - name: SYSTEM_PROMPT
           value: "<start_of_turn>model\nprompt<end_of_turn>\n"
         ports:
         - containerPort: 7860
---
apiVersion: v1
kind: Service
metadata:
  name: vllm-client-service
spec:
  type: LoadBalancer
  selector:
    app: vllm-client
  ports:
  - port: 8080
    targetPort: 7860